[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code
optimizer = true
optimizer_runs = 10000
chain_id = 31337

# Corrected remapping - add "contracts/" at the end
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
