[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code
optimizer = true
optimizer_runs = 10000
# # Monad Configuration
# eth-rpc-url="https://testnet-rpc.monad.xyz"
# chain_id = 10143
chain_id = 10143  # Monad Testnet chain ID
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]